'use strict';

/**
 * Clause library.
 *
 * Nothing in this file is ever generated by an LLM. It is the client's own
 * approved wording, versioned. The renderer only selects and substitutes.
 */

const COMPANY = {
  name1: 'ORRNA JAYA',
  name2: 'ENGINEERING & TRADING',
  regNo: '(NS0143763-K)',
  addr1: 'No. 22, Jalan Melati 1, Taman Desa Melati 3,',
  addr2: '71800 Putra Nilai, Negeri Sembilan Darul Khusus',
  tel: 'Tel/fax: 06 7998827/ 011-1065 6831',
  emailLabel: 'Email: ',
  email: 'ojet6831@gmail.com',
  signOff: 'RAVIE',
  signOffCompany: 'ORRNA JAYA ENGINEERING & TRADING',
  signOffCity: 'NILAI, Malaysia',
};

/** Section 2 - "Overview of standardized analyze and action". Selectable presets. */
const STANDARD_ACTION_PRESETS = [
  {
    key: 'mt-spindle-standard',
    label: 'M/T Spindle - Standard Recondition',
    version: 1,
    intro: 'The quotation is based on separate agreement regarding starting date for the reconditioning.',
    items: [
      'Disassembly and cleaning of spindle (excl.possible peripheral equipment).',
      'Cleaning and permeability control of lubrication- and cooling lines.',
      'Visual judgment of cause for failure.',
      'Measuring of bearing journals at temperature stable condition in respect to dimension, roundness and axial flatness to maximal bearing performance / endurance.',
      'Checking the critical components, parts, and surfaces.',
      'Checking of tool nose run \u2013 out, contact integrity and electrical components.',
      'Mounting, preloading and axial locking, of new high precision bearings.',
      'Clamp force control, wear inspection and lubrication of tool mechanism.',
      'Replacement of surfaced 0-rings.',
      'Verification of operating temperature at stated maximum speed',
      'Verification of vibration levels for mechanical and bearing related parameters.',
      'Generation of recondition protocols.',
    ],
  },
  {
    key: 'mt-spindle-inspection',
    label: 'M/T Spindle - Inspection & Report Only',
    version: 1,
    intro: 'The quotation is based on separate agreement regarding starting date for the inspection.',
    items: [
      'Disassembly and cleaning of spindle (excl.possible peripheral equipment).',
      'Cleaning and permeability control of lubrication- and cooling lines.',
      'Visual judgment of cause for failure.',
      'Measuring of bearing journals at temperature stable condition in respect to dimension, roundness and axial flatness.',
      'Checking the critical components, parts, and surfaces.',
      'Checking of tool nose run \u2013 out, contact integrity and electrical components.',
      'Generation of inspection protocols.',
    ],
  },
  {
    key: 'motorised-spindle-standard',
    label: 'Motorised / Built-in Spindle - Standard Recondition',
    version: 1,
    intro: 'The quotation is based on separate agreement regarding starting date for the reconditioning.',
    items: [
      'Disassembly and cleaning of spindle (excl.possible peripheral equipment).',
      'Cleaning and permeability control of lubrication- and cooling lines.',
      'Visual judgment of cause for failure.',
      'Measuring of bearing journals at temperature stable condition in respect to dimension, roundness and axial flatness to maximal bearing performance / endurance.',
      'Checking the critical components, parts, and surfaces.',
      'Insulation resistance and winding continuity test of motor stator.',
      'Checking of tool nose run \u2013 out, contact integrity and electrical components.',
      'Mounting, preloading and axial locking, of new high precision bearings.',
      'Clamp force control, wear inspection and lubrication of tool mechanism.',
      'Replacement of surfaced 0-rings.',
      'Verification of operating temperature at stated maximum speed',
      'Verification of vibration levels for mechanical and bearing related parameters.',
      'Generation of recondition protocols.',
    ],
  },
];

/**
 * Section 3 - "Others agreed actions".
 * Master catalog. Order is fixed; each quote stores a ticked/unticked state.
 * `defaultOn` reproduces the sample document's ticks.
 */
const AGREED_ACTIONS_CATALOG = [
  { key: 'incoming-test-run', label: 'Incoming test run', defaultOn: false },
  { key: 'precision-bearings', label: 'Precision bearings (Steel Ball)', defaultOn: true },
  { key: 'ir-or-spacer', label: 'Replacement of IR/OR Spacer', defaultOn: true },
  { key: 'complete-balancing', label: 'Complete Balancing', defaultOn: true },
  { key: 'taper-rework', label: 'Spindle shaft BT30  taper rework', defaultOn: true },
  { key: 'journal-rework', label: 'Spindle shaft bearing journal rework', defaultOn: true },
  { key: 'front-preload-spacer', label: 'Front bearing preload spacer replaced', defaultOn: true },
  { key: 'rear-preload-spacer', label: 'Rear bearing preload spacer replaced', defaultOn: true },
  { key: 'o-ring-replace', label: 'O Ring Replace', defaultOn: true },
  { key: 'in-house-test-run', label: 'In House Test Run', defaultOn: true },
  { key: 'dismantle-reassemble', label: 'Dismantle & Reassemble at Machine', defaultOn: true },
  { key: 'install-test-run', label: 'Install & Test Run Spindle at Machine', defaultOn: true },
  { key: 'transportation', label: 'Transportation (2 ways)', defaultOn: true },
  { key: 'workmanship', label: 'Workmanship', defaultOn: true },
];

/** Section 4 - "Please note" narrative. Rarely edited, but editable per quote. */
const PLEASE_NOTE = [
  'Price includes time & materials but exclude shipment costs. Stated service time referrers to normal working time and start by date of ordering and excludes return shipment time. ORRNA JAYA  (Spindle Service) will contact you for confirmation, if any change of conditions occurs at time of ordering which extend the service time.',
  'By absence of specified reconditioning requirements, ORRNA JAYA (Spindle Service) specification of requirements will apply.',
  'ORRNA JAYA (SPINDLE SERVICE) undertakings do not include correction if improper/faulty/inadequate origin design, if not separated agreed.',
  'At customer decision to interrupt agreed and started reconditioning process, the object will be returned to customer in the condition at the time for interruption (dismounted). Charges will be done corresponding to cost occurred.',
  'It is customer responsibility to assure the ancillary Machine Parameters and Components related to the serviced object, are checked, reset and/or adjusted during commissioning.',
];

/** Section 5 - "Conditions". Field-driven with defaults. */
const CONDITIONS_DEFAULTS = {
  validityDays: 30,
  paymentTermsDays: 30,
  deliveryDays: 14,
  otherConditions: 'ORRNA JAYA (SPINDLE SERVICE) General Condition \u2013 Repair & refurbishment Work.',
};

const NUMBER_WORDS = {
  1: 'ONE', 2: 'TWO', 3: 'THREE', 6: 'SIX', 12: 'TWELVE', 18: 'EIGHTEEN', 24: 'TWENTY-FOUR',
};

/**
 * Sections 6+ - General conditions of repair and refurbishment work.
 * Versioned and frozen onto each quote at issue time so a 2028 reprint of a
 * 2026 quote reproduces the 2026 terms.
 *
 * {{warrantyMonthsWord}} is the ONLY substitution, and it is fed from the same
 * warranty field printed on page 1. Previously these two were maintained by
 * hand in two places and could silently disagree.
 */
const GENERAL_CONDITIONS = {
  version: '2026-01',
  effectiveFrom: '2026-01-01',
  title: 'ORRNA JAYA\u2019s General conditions of repair and refurbishment work',
  clauses: [
    { h: '1. Applicability', p: ['These General Conditions shall apply in full on inspection, modification, repair and refurbishment work provided by ORRNA JAYA (\u201cthe Work\u201d) unless otherwise expressly agreed in writing by ORRNA JAYA. No other provisions shall be applicable, regardless of whether they were explicitly rejected or not in any individual case.'] },
    { h: '2. Scope of the Work', p: ['The scope of the Work to be provided shall be agreed in writing.'] },
    { h: '3. Pricing', p: [
      '3.1 If the parties agree on a fixed price for the Work, such price shall be based on the scope of the Work at the time of such agreement.',
      '3.2 If the parties do not agree on a fixed price, ORRNA JAYA shall be entitled to be paid for the Work performed according to ORRNA JAYA\u2019s current rates. ORRNA JAYA shall be reimbursed by the Customer for all other expenses (e.g. packing and transportation costs) actually incurred. Any price estimate given by ORRNA JAYA in respect of the Work shall not limit the payment ORRNA JAYA is entitled to recover under this provision.',
      '3.3 The prices shall be exclusive of transportation cost, insurance cost, value added tax, and, unless otherwise   agreed, any other taxes and duties.'] },
    { h: '4. Payment', p: [
      '4.1 ORRNA JAYA shall be paid in full not later than 30 days following the date of ORRNA JAYA\u2019s invoice if not otherwise separately agreed in writing.',
      '4.2 The Customer is not entitled to withhold or set off against any payments due to ORRNA JAYA on the basis of claims against ORRNA JAYA.'] },
    { h: '5. Subcontracting & spare parts', p: ['ORRNA JAYA shall be entitled to subcontract the Work or any part thereof to a third party. ORRNA JAYA shall be entitled to use any spare parts from any supplier, unless otherwise agreed with the Customer. Subcontracting will not affect ORRNA JAYA\u2019s obligations under this Agreement.'] },
    { h: '6. Technical documentation and repair requirements', p: ['The Customer shall inform ORRNA JAYA of the valid operating conditions and shall supply ORRNA JAYA with the technical documentation necessary for carrying out the work. The documentation shall remain the property of the Customer, and shall not be used by ORRNA JAYA or any subcontractor other than for the purposes of the Work. If the Customer fails to specify result requirements of the Work, ORRNA JAYA\u2019s definition thereof will apply'] },
    { h: '7. Risk of loss or damage', p: ['The risk of loss or damage to goods while outside the Customer\u2019s premises for the purpose of the Work (including risk of transportation) shall be borne by the Customer unless such loss or damage is due to gross negligence of ORRNA JAYA.'] },
    { h: '8. Time for completion', p: [
      '8.1 A time quoted for completion shall be binding only if it is expressly stipulated as such in writing.',
      '8.2 ORRNA JAYA is entitled to an extension of any binding time for Completion in the event of:',
      'a) any additional orders for the Work being given by the Customer and accepted by ORRNA JAYA, or',
      'b) Any agreed extensions of the scope of the Work, or',
      'c) Any cause of relief under clause 12, or,',
      'd) The Customer being in default of any of its obligations, if such event causes delay in the performance of the Agreement.'] },
    { h: '9. Reservations of title', p: ['Until receipt of all payment to be made under the Agreement, ORRNA JAYA retains the property in all accessory parts, spares, or replacement parts employed to the extent permitted by the law of the country of ORRNA JAYA.'] },
    { h: '10. Warranty', p: [
      '10.1 ORRNA JAYA shall, at its own expense, make good, by repair or replacement, any defects in the Work, or on the materials or parts used by ORRNA JAYA appearing within {{warrantyMonthsWord}} months after the Work was performed. The Customer shall notify ORRNA JAYA in writing without delay of any such defect.',
      '10.2 ORRNA JAYA\u2019s warranty shall apply only to defects that appear under normal operating conditions, under proper use and only to the extent the defects can be assignable to ORRNA JAYA\u2019s performance of the Work. It shall not extend to defects arising from transportation, the Customer\u2019s faulty maintenance, faulty erection, faulty installation or storage. Nor does it extend to defects arising from alterations in the Work carried out without ORRNA JAYA\u2019s prior consent in writing, or from repairs carried out by the Customer, or any third party, or from normal wear and tear. ORRNA JAYA\u2019s warranty shall not apply on defects on, or defects arising from, materials or parts supplied by the Customer'] },
    { h: '11. Limitation of liability', p: [
      '11.1 ORRNA JAYA\u2019s liability is limited only to the Work and/or parts supplied by ORRNA JAYA or its contractors and the express warranty set forth in Section 10 is exclusive, and no other warranties of any kind, whether statutory, written, oral or implied, including warranties for fitness for a particular purpose or merchantability, shall apply.',
      '11.2 Without limitation of Section 11.1 ORRNA JAYA\u2019s total liability to the Customer for all claims of any kind, whether based upon contract, tort (including negligence), strict liability or otherwise, for any loss or damage arising out of, connected with, or resulting from the performance or breach of this Agreement shall in no case exceed 10 per cent of the price paid by the Customer for the Work in question.',
      '11.3 In no event, whether as a result of breach of contract, tort liability (including negligence), strict liability or otherwise, and whether arising before or after completion of ORRNA JAYA\u2019s obligations under the Agreement, shall ORRNA JAYA be liable to loss of use, profits or revenue, or special, consequential, or penal damages of any nature.'] },
    { h: '12. Force majeure', p: ['Either party shall be released from performance of its obligations under the Agreement to the extent, and for so long as, the performance of the Agreement is impeded by reason of the force majeure. The party claiming force majeure circumstances shall give prompt notice of the commencement and cessation of any such circumstances. For the purpose of this Article the expression \u201cforce majeure\u201d means, but shall not be limited to, industrial dispute, fire, mobilization, requisition, embargo, currency transfer prohibitions, insurrection, lack of means of transport, restrictions of the use of energy, and generally any circumstances which are beyond the control of the parties and hinder performance by one party of his obligations. If circumstances of the force majeure continue for a period exceeding 6 months either party shall be entitled to terminate the Agreement by notice in writing without incurring any further liability.'] },
  ],
  closing: 'We are looking forward to your order and await your response prior further actions is taken.',
};

const INTRO_PARAGRAPHS = [
  'ORRNA JAYA (SPINDLE SERVICE) has the pleasure to offer our undertaking to recondition your spindle and take necessary action to refurbish the wear and damages which appeared during our analyze process and which deviates from ORRNA JAYA  (SPINDLE SERVICE) acceptance criteria for M/T spindles.',
  'Based on analyze and needed components, we offer the reconditioning to perform at below mentioned price and service time.',
];

function warrantyWord(months) {
  const n = parseInt(months, 10);
  return NUMBER_WORDS[n] || String(months || '').toUpperCase();
}

module.exports = {
  COMPANY,
  STANDARD_ACTION_PRESETS,
  AGREED_ACTIONS_CATALOG,
  PLEASE_NOTE,
  CONDITIONS_DEFAULTS,
  GENERAL_CONDITIONS,
  INTRO_PARAGRAPHS,
  warrantyWord,
};
